version: '3.7'
services:
  app:
    image: jamesmjkim/denostore-demo
    restart: always
    container_name: 'denostore-demo'
    build: .
    ports:
      - '3000:3000'
    networks:
      - deno
    volumes:
      - .:/usr
      # - node_modules:/usr/node_modules
    depends_on:
      - redis
    command: deno run --allow-all server/server.ts
  redis:
    image: jamesmjkim/redis
    container_name: 'redis-db'
    ports:
      - '6379:6379'
    restart: always
    command: redis-server
    volumes:
      - cache:/data
volumes:
  # node_modules:
  cache:
    driver: local
networks:
  deno: {}
