version: '3.7'
services:
  app:
    image: jamesmjkim/denostore-demo
    restart: always
    container_name: 'denostore-demo'
    ports:
      - '80:3000'
    environment:
      - DENO_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: jamesmjkim/redis
    container_name: 'redis-db'
    ports:
      - '6379:6379'
    restart: always
    command: redis-server
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
